server.port: 8888

spring: 
 datasource: 
  url: jdbc:mysql://127.0.0.1:3988/express_db?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
  username: root
  password: pppsswwdd
  driver-class-name: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  minIdle: 5
  maxActive: 200
  maxWait: 30000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j

# Mybatis configs
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mine.domain
  
  
redis.hostname: 127.0.0.1
redis.port: 6379
redis.password: okletsgo

# logging
logging.level.root: INFO
#logging.level.org.springframework.web=DEBUG
logging.file: /data/logs/express_storage/forever.log
